### ISSUE TITLE
redstone impregnated stick not transfering power correctly

### ISSUE THREAD

**Issue by wheelerchristopherg** [amadornes/SCM-Localization-Issues#100]
![2016-11-06_00 37 45](https://cloud.githubusercontent.com/assets/4797555/20035612/f742f1ca-a3b9-11e6-84a8-abb9066d2f07.png)
This picture shows what I mean. The redstone impregnated stick on the right side doesn't transfer any power down.
 Right after I took this screenshot, I flipped the lever to the left and the circuit crashed. Here's the log for that: https://gist.github.com/aaf0bce08eb93bb773a36a4f4c93bff1

**Comment by GirafiStudios** [comment]
Amadornes fixed that earlier today, so should be fixed in next build :)

**Comment by amadornes** [comment]
Yep, yet another post bug. Already fixed! :)
