### ISSUE TITLE
Input on North/South corners not working

### ISSUE THREAD

**Issue by useless-penguin** [amadornes/SCM-Localization-Issues#104]
sorta breaks rotation of circuits If corner connections are used. affects both bundled and normal lines.
![2016-11-06_03 58 09](https://cloud.githubusercontent.com/assets/6659696/20036422/20f12304-a3d6-11e6-84f5-e672aae92361.png)
output seems to work on all corners.

Note: North/South I/O can't be hooked up without rotating circuit

**Comment by amadornes** [comment]
Duplicate of #81. Already fixed :)

**Comment by useless-penguin** [comment]
Sorry, forgot to check.
 #96 also touches on this.
