### ISSUE TITLE
Bundled cables appear to be broken

### ISSUE THREAD

**Issue by techninja1008** [amadornes/SCM-Localization-Issues#106]
Bundled cables appear to be buggy.

Pastebin with modlist from log, no exceptions were found so I didn't include the whole log:
[pastebin](http://pastebin.com/RppA0V10)

(In the image with the button, it is currently pressed)

![2016-11-06_14 09 53](https://cloud.githubusercontent.com/assets/4208789/20038611/92fd87c8-a42e-11e6-855a-3d5371aef840.png)
![2016-11-06_14 31 54](https://cloud.githubusercontent.com/assets/4208789/20038613/9301ab46-a42e-11e6-9d37-48f156ef42db.png)
![2016-11-06_14 32 34](https://cloud.githubusercontent.com/assets/4208789/20038612/930145de-a42e-11e6-9444-edeb27ea8df3.png)

**Comment by amadornes** [comment]
This should all be fixed in the next build :)

**Comment by techninja1008** [comment]
Awesome!
