### ISSUE TITLE
A copying machine

### ISSUE THREAD

**Issue by LousyLynx** [amadornes/SCM-Localization-Issues#109]
Say you need a bunch of custom 7-seg displays. Like 5 stacks. How would you do that? (And why would you need that many?) You would have to create then all, or go into creative, and copy them. I feel like a machine that you put a circuit into, and lets you make a whole bunch would be awesome. You would put your circuit it, give it a name, and it would tell you how many of each part you need to make a specific amount. Then it... well, makes them. Then you could make a community one on a server, and everyone would be able to use your circuits, or whatever you make. I think that would be very cool.

**Comment by mcenderdragon** [comment]
You can make a Blueprint and If you have the needed resources they will be used when you place the blueprint on the circuid

**Comment by LousyLynx** [comment]
Didn't know that :P Guess that goes in the trash :P

**Comment by amadornes** [comment]
Yeah, you can use blueprints, but once the Component Tray is implemented you'll be able to combine a plate with the component tray (if it has the required items) and a blueprint to make a copy of it in your inventory :)
