### ISSUE TITLE
RS Latch Clock?

### ISSUE THREAD

**Issue by gudenau** [amadornes/SCM-Localization-Issues#117]
I was attempting to make a memory bit and I managed to make a clock out of it, this does not appear to be intended behavior.
[![Video](https://i.ytimg.com/vi/HfMSiNpE1Pw/hqdefault.jpg)](https://www.youtube.com/watch?v=HfMSiNpE1Pw)

**Comment by amadornes** [comment]
SCM torches work on a 1-tick basis, so if what you got was a 1-tick clock, then yes, it's intended. You'll have to extend the ticks you send to your RS-latch.

**Comment by gudenau** [comment]
Okay, I guess I just happened to input things just right.
