### ISSUE TITLE
[1.0.2] Crash when trying to place circuit on circuit.

### ISSUE THREAD

**Issue by wesserboy** [amadornes/SCM-Localization-Issues#119]
I tried to place this circuit:
https://gist.github.com/anonymous/95f45dd676ff0e830072219f5a958ed8
On an empty plate, and it crashed. (crashlog commented underneath the gist).

It's the same crash as #98. But since you said it shouldn't happen in 1.0.2 I thought I would create a new issue.

**Comment by amadornes** [comment]
The issue had two halves, one that involved sending the tag to the client (which is fixed) and that one, which I haven't fixed yet. That's why #98 isn't closed ;)
