### ISSUE TITLE
Output of IC is colour-sensitive in RS+Bundled mode

### ISSUE THREAD

**Issue by Inari-Whitebear** [amadornes/SCM-Localization-Issues#120]
Using this circuit: https://gist.github.com/anonymous/07e43a1926933492459d2dacb299fdf3
And putting it into other circuits as-is, it seems and output cable has to be white to receive the signal.

While I believe it should receive it in any colour since it is RS+Bundled?

Example of it being used:  https://gist.github.com/anonymous/4e1806d9ae550c7c41a40c340afd119c

**Comment by Inari-Whitebear** [comment]
Bug #2 : When you place that example blueprint (the second link) down, you see the output of the right IC turn off a tick or so after being placed. But the levers are on, thus the output should be on. If you turn the levers off and on again, it outputs correctly.

**Comment by amadornes** [comment]
Welp... Couldn't fix it, did something completely unrelated it, came back to it... and it worked... Oh well :P
