### ISSUE TITLE
SCM Import does not like dashes in gist name :D

### ISSUE THREAD

**Issue by Inari-Whitebear** [amadornes/SCM-Localization-Issues#121]
So when I try to import a gist from my own account, it goes "Invalid URL!" Apparently it does not like the "-" in "Inari-Whitebear", because when I remove that it just tells me it had an error when reading the blueprint gist (since there obviously is none then :D).

**Comment by amadornes** [comment]
Well it's not really meant to read from people's gists, but rather from the "anonymous" user/no user :P

**Comment by Inari-Whitebear** [comment]
But to share circuits it would kind of be nice to have them in your own folder of gists

**Comment by amadornes** [comment]
Ehh... I guess...

**Comment by amadornes** [comment]
Fixed!
