### ISSUE TITLE
Colored Redstone-Impregnated Sticks

### ISSUE THREAD

**Issue by gudenau** [amadornes/SCM-Localization-Issues#122]
Could you allow the Redstone-Impregnated Sticks to be colored? I have had a couple issues while using a bundled cable right next to a stick because the stick was light gray and would not connect, this would also allow some interesting vertical circuitry.

**Comment by amadornes** [comment]
Redstone-Impregnated Sticks have always been grey so you can't use them to send bundled signals and, in fact, in the next build that signal won't even be able to go into a bundled cable. They're meant to work like that and make you think more when building your circuits ;)

**Comment by gudenau** [comment]
*shakes first*

Guess I'll just have to make mine bigger. :-P
