### ISSUE TITLE
Drag-drawing wire on vertical connected circuits

### ISSUE THREAD

**Issue by Inari-Whitebear** [amadornes/SCM-Localization-Issues#123]
So when I have two circuits on a wall like so:
X
X

And I start on the lower one, and drag onto the top one, and let go. It actually adds what I dragged on the upper one to the lower one as an upper layer o.o

https://dl.dropboxusercontent.com/u/18783800/ShareX/2016/11/2016-11-06_21-02-39_YZgmDh.gif Example

**Comment by amadornes** [comment]
Fixed!
