### ISSUE TITLE
Error circuit

### ISSUE THREAD

**Issue by dpeter99** [amadornes/SCM-Localization-Issues#125]
https://gist.github.com/3c8d9bbb501ca245d98d2cbc6f22d21b
![2016-11-06_21 51 24](https://cloud.githubusercontent.com/assets/7725817/20041546/2d91b7aa-a46b-11e6-8705-51c6f664e019.png)

Enviroment:
SCM: 1.0.2

**Comment by amadornes** [comment]
From the crashlog it looks like a lever is backfeeding into itself. I'll look into it :)

**Comment by amadornes** [comment]
Should be fixed now :)
