### ISSUE TITLE
Couple minor bugs

### ISSUE THREAD

**Issue by Exidex** [amadornes/SCM-Localization-Issues#126]
- [x] You can't pick up the Redstone Alloy Wire using middleclick in Creative mode.
- [x] Circuit in the Blueprint: SEQ is broken.

- [x]  The lever is propagating signal to the side after being rotated.

![2016-11-06_22 04 03](https://cloud.githubusercontent.com/assets/16986685/20041671/01c7eb10-a46d-11e6-9d82-766b53365224.png)

SCM: 1.0.2

**Comment by amadornes** [comment]
Fixed!
