### ISSUE TITLE
Non-conductive plate not letting colored signal through

### ISSUE THREAD

**Issue by wheelerchristopherg** [amadornes/SCM-Localization-Issues#132]
![2016-11-06_21 01 09](https://cloud.githubusercontent.com/assets/4797555/20045212/cd137c66-a464-11e6-93e8-a3cf4183924d.png)
The top circuit uses a non-conductive plate to prevent back-flow on the white line, but instead no current is allowed through going up. The second circuit is built the same but with a conductive plate instead. The non-conductive plate works perfectly for non colored wires.

**Comment by Mr-Gelo** [comment]
I have encountered the same problem in my circuit in SCM-1.0.2

**Comment by jdplecke** [comment]
http://prntscr.com/d4ckbp
Can confirm it works with grey but not with other colours.

**Comment by amadornes** [comment]
This is due to a bug that prevents vertical wire from connecting (internally) to regular wire. I thought I fixed it in 1.0.2, but I guess not...

**Comment by jdplecke** [comment]
It seems to be very unpredictable, I did some messing around and sometimes it does work just fine.

**Comment by amadornes** [comment]
Fixed!

**Comment by jdplecke** [comment]
http://prntscr.com/d5ap3i

This seems to be a problem still

**Comment by amadornes** [comment]
Fixed! Signals could go up in 1.0.3 but apparently not down... :P

**Comment by jdplecke** [comment]
http://prntscr.com/d62hox

It still seems to happen with bundled sticks

**Comment by simsonmeno** [comment]
Vertical diodes don't work in complex circuits in version 1.0.4
![scm 14x8bit addressable storage expandable](https://cloud.githubusercontent.com/assets/10546463/23105903/5d02d91a-f6e6-11e6-9950-d236400a461b.png)
https://gist.github.com/fa5a441d8f290173495bbd45b969020d
https://gist.github.com/f6589613f3565905a87eba327bd69085
https://gist.github.com/64e24c93fbac72912d990a2f5cf939aa
https://gist.github.com/cb3b882669655cf7cac3be4db9738b5d

**Comment by dokranke** [comment]
@simsonmeno Did you tried to just use a single module pf that giant circuit.

I guess the vertical diodes don't work because of the complexity which maybe throws stackoverflow error (because I can't even toggle a single (nearly filled) circuit of mine without getting these).

That happens because when 1 tile updates, it updates the whole circuit recursivly
