### ISSUE TITLE
Bundled Cables don't seem to update when copied over

### ISSUE THREAD

**Issue by kboy101222** [amadornes/SCM-Localization-Issues#134]
Using [this circuit](https://gist.github.com/anonymous/e9d18a32acaf3a3b3ce9c27b603b616b)

Whenever I use the blueprint to copy the circuit, the bundled cables don't activate, as shown [here](http://imgur.com/EJDeihq.gifv)

**Comment by kboy101222** [comment]
As well, I'll occasionally get the BCOD. Here's the log http://pastebin.com/mWtkfH2E

**Comment by kboy101222** [comment]
According to Amadornes, this is fixed in 1.0.3

**Comment by amadornes** [comment]
Should be fixed now :)
