### ISSUE TITLE
[1.0.2] Game crash when changing Quartz Resonator's delay

### ISSUE THREAD

**Issue by Mr-Gelo** [amadornes/SCM-Localization-Issues#135]
Here is a crash report: http://pastebin.com/K8xCBKs9
I used SCM ver. 1.0.2 and the latest Forge ver. 12.18.2.2122

The crash appeared when I have changed Quartz Resonator's delay from 1 to 2 ticks (I'm not 100% sure it has been 'from 1 to 2 ticks', but I'm 100% sure I have been working in QR's GUI). The original circuit and the world survived, but I can not reproduce the crash, even on this same circuit :(

**Comment by amadornes** [comment]
Should be fixed in 1.0.3 :)
