### ISSUE TITLE
NPE with Bundle Connecting to Circuit-on-Circuit

### ISSUE THREAD

**Issue by quantumdude836** [amadornes/SCM-Localization-Issues#136]
https://gist.github.com/anonymous/d4ca7f0f472f50a3d441b0af5c83a14a

**Comment by amadornes** [comment]
Already fixed in 1.0.3. Will release tonight :)

**Comment by elwooha6** [comment]
Any ETA on the 1.0.3 update? Not trying to be impatient but this bug is really holding me up.

**Comment by amadornes** [comment]
Yeah, sorry! I had to go a bit earlier than I expected last night so I couldn't release the new build. I'll be out in a few hours for sure :)

**Comment by elwooha6** [comment]
sweet, thanks 👍
