### ISSUE TITLE
[1.0.2] Clicking on a wire with palette and brush causes odd behavior.

### ISSUE THREAD

**Issue by Mr-Gelo** [amadornes/SCM-Localization-Issues#137]
When right-click on a wire with Palette and brush (in right hand)
or when right-click with an empty hand and having Palette and brush in left-hand-slot
there will be odd wire's behavior (look at he screenshots).

This ONLY works when clicking a wire with THE SAME COLOR as in the Palette. Clicking with different color will just change the color and won`t cause any odd things.
&nbsp;
&nbsp;
![2016-11-07_14 29 37](https://cloud.githubusercontent.com/assets/23279054/20051261/bb8e2cce-a500-11e6-90d8-cb706f727be3.png)
Here is simple circuit.
&nbsp;
&nbsp;
![2016-11-07_14 29 47](https://cloud.githubusercontent.com/assets/23279054/20051461/b2a9fa7e-a501-11e6-85ab-dab670f9e5fa.png)
And here I clicked it. Look at the right torch :(
&nbsp;
&nbsp;
![2016-11-07_14 50 28](https://cloud.githubusercontent.com/assets/23279054/20051508/f48652a8-a501-11e6-8dfb-686e8917596b.png)
This works for any color, all you need is the same color on Palette and on wire.

**Comment by amadornes** [comment]
I've certainly noticed this before, yeah... I'll look into it :)

**Comment by amadornes** [comment]
Fixed!
