### ISSUE TITLE
Weird Circuit Crash

### ISSUE THREAD

**Issue by gord0213** [amadornes/SCM-Localization-Issues#142]
Hey so i was working with SCM and when i copied and placed down the circuit in the hole spot. his is the video of it happening(dont mind the stuttering) https://db.tt/8aQ9MPiB , Here is a link to the circuit https://gist.github.com/3d37322cc4a92dc450488cb9b3b51037 , this is also in 1.0.2

**Comment by amadornes** [comment]
This is a better place to post it than the subreddit, yeah ;)

But I honestly have no clue what's going on... I'll have a look :)

**Comment by gord0213** [comment]
Yeah, Sorry about that posted it before reading :p

**Comment by amadornes** [comment]
I can't reproduce it, so I guess I've accidentally fixed it already :P
