### ISSUE TITLE
BCOD on pulsar and lever connections

### ISSUE THREAD

**Issue by Nezbro** [amadornes/SCM-Localization-Issues#146]
https://gist.github.com/anonymous/942394f3b8bce6e9b2c12fc72bf61eaa

![2016-11-07_18 07 14](https://cloud.githubusercontent.com/assets/23294586/20081407/15d02bce-a515-11e6-8490-661122b98ffb.png)

Every time I go to give the pulsar an option to output it BCOD me

**Comment by amadornes** [comment]
Fixed!
