### ISSUE TITLE
(Feature Request) Modulus Operator

### ISSUE THREAD

**Issue by AgentA1cr** [amadornes/SCM-Localization-Issues#148]
I love this mod so far, but one thing I quickly noticed was the lack of a modulus operator, or alternatively, a way to retrieve the remainder from a division operator. Would you consider adding this feature?

**Comment by amadornes** [comment]
When I implemented math operations my idea was to have people do their own modulus (since it's just subtracting the result of the division * divider from the original input), but I could add it, yes.

**Comment by AgentA1cr** [comment]
Awesome. Thanks, and keep up the great work. :)

**Comment by amadornes** [comment]
If you're okay with building it yourself (it really isn't that complicated :P), I guess I'll close the issue :)
