### ISSUE TITLE
Bundled stick bug

### ISSUE THREAD

**Issue by bence98** [amadornes/SCM-Localization-Issues#152]
Placing the bundled stick on a bundled network will cause it to behave abnormally: if any bundled channel is active, it'll set ALL channels to 255 (checked with the Multimeter). As you can see on the image below, the two lamps are wired exactly the same (both on channel black), except one is connected to a bundled stick. I give a signal to a random channel (in this case, white), and the lamp with the stick turns on for some reason.
http://imgur.com/gallery/QZGtE
I hope it'll get fixed soon, because I'm in the middle of designing a complex gate.

**Comment by amadornes** [comment]
I'm not exactly sure why this happens... but I guess I've accidentally fixed it while fixing other things :D
