### ISSUE TITLE
Pulse Former doesn't seem to work

### ISSUE THREAD

**Issue by Drullkus** [amadornes/SCM-Localization-Issues#153]
I've got a Pulse Former design that's arguably the same design, but somehow they act... Differently. Output is not detected at all in SCM's blueprint version. It is, on mine.

![pulseformer](https://cloud.githubusercontent.com/assets/5010174/20119196/6e65ffb4-a5bc-11e6-89b3-736762a9e340.gif)

**Comment by Drullkus** [comment]
I found your issue:
![2016-11-08_14 10 01](https://cloud.githubusercontent.com/assets/5010174/20119345/0ebca896-a5bd-11e6-9b52-1bf514928a78.png)

**Comment by amadornes** [comment]
Yep. Blueprints are sorta broken it seems. I'll test and re-package them before I push 1.0.3 :)

**Comment by amadornes** [comment]
Fixed!
