### ISSUE TITLE
[1.10.2] [Duplication Bug] Redstone becoming infinitely duplicatable  

### ISSUE THREAD

**Issue by SnowShock35** [amadornes/SCM-Localization-Issues#155]
Hi Ama,

So quick bug for you, Not found by me. However, I thought best to report it. Here's the details 

### Important Information

- Minecraft 1.10.2
- Minecraft Forge 12.18.2.2120
- Super Circuit Maker 1.0.1

### Issue Description 

Redstone edgecase with BUD updates from trapdoors unhandled by Super Circuit Maker allowing vanilla(?) dupe bug to occur

### Issue Media

http://jaffa.cat/2016/11/05/Tz4zUV.webm

**Comment by Mr-Gelo** [comment]
Since SCM is only for Minecraft 1.10.2 it's strange to see "1.10.2" in the issue's name :/

**Comment by SnowShock35** [comment]
@Mr-Gelo Sorry force of habit. Not to mention I was tired too

**Comment by amadornes** [comment]
Fixed!

**Comment by SnowShock35** [comment]
Thanks Ama <3
