### ISSUE TITLE
Issues when trying to make memory cells

### ISSUE THREAD

**Issue by thecodewarrior** [amadornes/SCM-Localization-Issues#157]
I've been making memory cells, and repeatedly had them error on me. I can't exactly tell what's going on, but here are some of the logs:

- https://gist.github.com/140f1a346675c1f11009c51cd5435c2a
- https://gist.github.com/375976de303fe9d1361bdb997cb56f9e
- https://gist.github.com/e024f76bf051ddcae5477d8279eef593
- https://gist.github.com/5ec27a5edfd1ba569dafc5269d82ebd0

**Comment by gDKdev** [comment]
**Working:**
- [circuit inside of one](https://gist.github.com/140f1a346675c1f11009c51cd5435c2a)
- [second](https://gist.github.com/375976de303fe9d1361bdb997cb56f9e)
- [forth](https://gist.github.com/5ec27a5edfd1ba569dafc5269d82ebd0)

**Not working:**
- [one](https://gist.github.com/140f1a346675c1f11009c51cd5435c2a)

**Don't know**
- [third](https://gist.github.com/e024f76bf051ddcae5477d8279eef593) (reason: part of something bigger??)

**Comment by amadornes** [comment]
I'll take @gDKdev's word that they work except for the first one, and I can tell you why it doesn't.  Circuits in circuits don't auto-output to other circuits. You need wires in between :P
