### ISSUE TITLE
Adder have wrong output

### ISSUE THREAD

**Issue by Lamkac** [amadornes/SCM-Localization-Issues#159]
[https://www.youtube.com/watch?v=0VpmXzgyuyM](https://www.youtube.com/watch?v=0VpmXzgyuyM)

Adder and sometimes subtractor giving weird output

**Comment by amadornes** [comment]
Mind sending me a blueprint that I can test with?

**Comment by Lamkac** [comment]
https://gist.github.com/anonymous/611505983b05a491c5af9eb565b47721

**Comment by amadornes** [comment]
Works fine on my end... Soo... I guess just wait a few hours for 1.0.3? :P
