### ISSUE TITLE
Enhancement: Vertical in- and outputs

### ISSUE THREAD

**Issue by gDKdev** [amadornes/SCM-Localization-Issues#160]
It would be great to have vertical in- and outputs on cables, so we could for example receive/change a torch state from the top or bottom, get a signal from the top or bottom of an ender pulsar, change a lever...

A lever also could get a extra functionality on top or bottom: a pulse on state change

**Comment by amadornes** [comment]
You mean... Exactly what happens when you place vertical wire and a plate below a component? :P
http://ss.amadornes.com/ama-1478709988-1204

**Comment by gDKdev** [comment]
Yes but i need that for torches, a in and out

**Comment by amadornes** [comment]
I guess it's not fixed... huh...

**Comment by gDKdev** [comment]
Ehm, this is not a bug, but a enhancement. There is no problem like it is right now, it just could be a bit better.

**Comment by gDKdev** [comment]
Got a idea how you maybe could implement it easily: just 2 new tiny plates, one for vertical inputs and one for vertical outputs. Because you to have the redstone circuit plate or a tiny plate under every component

**Comment by amadornes** [comment]
So... the different diode modes of the nonconductive plate... yeah... nah... Components either output or input on a specific face (vertically), not both. The toughness of vertical wiring is part of the circuit-building challenge. Though if a component wants to do that, I guess NC-Plates will work :P

**Comment by amadornes** [comment]
Fixed!
