### ISSUE TITLE
Bug: Bundled cable stays on for ever [Possible Duplicate]

### ISSUE THREAD

**Issue by gDKdev** [amadornes/SCM-Localization-Issues#161]
[This circuit](https://gist.github.com/c59b80518aa699e014f6c4bed24a55af) is a 16-bit memory cell power (north: in, east: write-lock, south: out, west: read-lock).

Just give it a pulse in any color on north, the input should be off now, but is stays powered.
Same with the output after a reading a high value.

Possible duplicate with #86

**Comment by amadornes** [comment]
Yes, this is the same thing as #86. To prevent this from happening, do your inner circuit I/O using regular colored cable instead of bundled.

**Comment by gDKdev** [comment]
Followed your advice and replaced every single bundled cable, now i get an error circuit every time i place it. [Here](https://gist.github.com/f138827436bd17043c4d07cca82cff94) is the gist

**Comment by amadornes** [comment]
No crashes here. Just wait for 1.0.3 :P

**Comment by drbleblo** [comment]
This issue still persists any estimates on when it will be fixed?

**Comment by amadornes** [comment]
I can't say for sure because I'm not sure how I'm going to address it yet, sorry :/
