### ISSUE TITLE
Enhancement: Tiny torches

### ISSUE THREAD

**Issue by gDKdev** [amadornes/SCM-Localization-Issues#165]
Put a redstone torch inside a crafting table and viola you get tiny torches that are only one tile tall instead of two. Making some circuits compacter.

**Comment by Mr-Gelo** [comment]
Yeah, I would like this too!

**Comment by amadornes** [comment]
Uhh... yeah... no. There's a point where things stop being useful and start being OP, and this is it. Torches are 2-tall for a reason, and that's for balance purposes :P

**Comment by gDKdev** [comment]
I guess it doesn't really matter, the mod is soo overpowered as it is...
But instead of this we need the possibility for i/o on a torch from every side

**Comment by amadornes** [comment]
Small circuits != OP. There's a pretty good balance in the mod as is, and a half-size torch should have half the complexity of a normal torch, but be way more powerful? That kinda defeats the point. Same reason I don't include upside down torches. It's about engineering your own solution to problems, not getting one right off the bat. If I wanted that, you wouldn't get to customize gates and instead just use the ones I provide.
