### ISSUE TITLE
Colored wires work incorrectly when inside Integrated Circuits

### ISSUE THREAD

**Issue by Mr-Gelo** [amadornes/SCM-Localization-Issues#166]
Here I have a simple NOT-gate with colored wires:
![2016-11-10_00 28 55](https://cloud.githubusercontent.com/assets/23279054/20149788/61287244-a6e5-11e6-9e8a-4e13ff795dd5.png)
Here I placed it inside other circuit but it doesn't work correctly. Instead it pulses dark and than stays on forever. Every time I turn the lever on - it pulses again.
![2016-11-10_00 29 28](https://cloud.githubusercontent.com/assets/23279054/20149794/64c4a9ea-a6e5-11e6-9a4d-60f2081ecfa5.png)
But if I color one piece of wire...
![2016-11-10_00 30 05](https://cloud.githubusercontent.com/assets/23279054/20149795/6726fd5a-a6e5-11e6-9933-80d074c6637a.png)
It works just fine:
![2016-11-10_00 30 19](https://cloud.githubusercontent.com/assets/23279054/20149797/68c87648-a6e5-11e6-8fcd-97e3b335049e.png)
Using SCM 1.0.2

**Comment by amadornes** [comment]
Already fixed :)
