### ISSUE TITLE
Lever Crashes Circut

### ISSUE THREAD

**Issue by AuraTsuki** [amadornes/SCM-Localization-Issues#168]
[link](http://i.imgur.com/rki642q.png) placing a tiny pile of redstone on the bottom left like this [here](http://i.imgur.com/4mZ2TBi.png) , will result in a circuit crash a second or 2 after. Here's the crash log https://gist.github.com/anonymous/5a511bacec61f96dc7661a522614f72b

Also making [this](http://i.imgur.com/NhHQdWG.png) and flipping the lever will crash it. Here's the crash log for this one too https://gist.github.com/anonymous/9a7309d00e171654f4d6940b2f22e9e5

**Comment by amadornes** [comment]
Yep. Already fixed :)
