### ISSUE TITLE
Bug: Random circuit crashing after long runtime

### ISSUE THREAD

**Issue by gDKdev** [amadornes/SCM-Localization-Issues#169]
I kept minecraft open for about 48h, now even a circuit as simple as [bundled cable <-> colored cable <-> lever](https://gist.github.com/335615b4c85293be18a1e65e7ff366af) crashes every single circuit. [Here](https://gist.github.com/f138827436bd17043c4d07cca82cff94) is a more or less complex one, that crashes every time on placing.

Crashlog:
[fml-client-latest.log.txt](https://github.com/amadornes/SCM-Localization-Issues/files/581873/fml-client-latest.log.txt)

EDIT: Seems to crash every single time, not only after long time

**Comment by amadornes** [comment]
Already fixed!
