### ISSUE TITLE
Bug: All i/o's on the edges are broken

### ISSUE THREAD

**Issue by gDKdev** [amadornes/SCM-Localization-Issues#172]
When I place down any circuit down in 1.0.3, which was made with 1.0.2 ([like this](https://gist.github.com/f438ce62ec0d4df791aaff6a4b036376)), surround it by blank circuits and connect and power the inputs nothing is going to happen. I need to replace them with new ones to work (also on the outputs).

Tested with about 20 different circuits.

EDIT: Just noted that i can place non of them inside another circuits and also can't export them (link above is from a previous issue). Downgraded because for me 1.0.3 is useless when i can't place a circuit inside another one, too sad :( [fml-client-latest.log.txt](https://github.com/amadornes/SCM-Localization-Issues/files/582141/fml-client-latest.log.txt)

**Comment by amadornes** [comment]
Should be fixed now
