### ISSUE TITLE
[1.0.3][MP] Cicruit  disappear

### ISSUE THREAD

**Issue by marcin212** [amadornes/SCM-Localization-Issues#173]
Picking up the cicruit form the inventory and puting it back makes it disappear.

**video:** https://youtu.be/R6ZbbYGOoaY
**forge:** 12.18.2.2122

**mods:**
- jei_1.10.2-3.9.0.246
- MCMultiPart-1.3.0-universal
- SuperCircuitMaker-1.0.3

**Comment by amadornes** [comment]
Fixed!
