### ISSUE TITLE
[1.0.3][MP]  Circuit in circuit  and blueprint on multiplayer not working

### ISSUE THREAD

**Issue by marcin212** [amadornes/SCM-Localization-Issues#174]
**video:** https://youtu.be/T01KiD8y86Y

**forge:** 12.18.2.2122

**mods:**
- jei_1.10.2-3.9.0.246
- MCMultiPart-1.3.0-universal
- SuperCircuitMaker-1.0.3

**Comment by amadornes** [comment]
Should be fixed! :D
