### ISSUE TITLE
circuits on circuits not working

### ISSUE THREAD

**Issue by reinder-s** [amadornes/SCM-Localization-Issues#177]
using 1.0.3

![2016-11-10](https://cloud.githubusercontent.com/assets/11552821/20165650/799cca3a-a70f-11e6-8e15-da8d0f905c9b.png)
![2016-11-10 2](https://cloud.githubusercontent.com/assets/11552821/20165651/799d4bb8-a70f-11e6-87c4-21664fd9ae9f.png)
![2016-11-10 3](https://cloud.githubusercontent.com/assets/11552821/20165652/799e3bae-a70f-11e6-9666-f48f56e6a38e.png)

**Comment by ReTeYeZ** [comment]
Same issue for me.
AND-GATE:
![2016-11-10_11 02 07](https://cloud.githubusercontent.com/assets/5409380/20172413/3fa28cf4-a735-11e6-8f00-3c76771f64b4.png)

The same gate on a circuit:
![2016-11-10_11 04 11](https://cloud.githubusercontent.com/assets/5409380/20172465/7d23a90a-a735-11e6-801e-1589df67ccf0.png)

It's interesting though that circuits I've placed before the 1.0.3 update do work:
![2016-11-10_10 55 03](https://cloud.githubusercontent.com/assets/5409380/20172219/711fde5e-a734-11e6-9825-bebc166c4093.png)
(see that AND-GATE at the front)

SSC 1.0.3
MCMP 1.3.0
Forge 12.18.2.2123

**Comment by wesserboy** [comment]
Relogging seems to fix this, you might wanna give that a try.
This is explained in #183

**Comment by amadornes** [comment]
Fixed!
