### ISSUE TITLE
Enhancement: Circuits, Blue-/Redprints and Anvils

### ISSUE THREAD

**Issue by gDKdev** [amadornes/SCM-Localization-Issues#178]
If i have more than one circuit or blueprint in my inventory i usually rename them in an anvil.
But as soon as i place a named circuit down it lost it's name.

Could you save the name in anyway?
Also every time you override a Blue-/Redprint it resets it's name.

**Comment by amadornes** [comment]
Labelling machine is coming in 1.1.0. And yes, the name is reset because all the data of the circuit is copied to the blueprint and overrides the previous data.
