### ISSUE TITLE
middle click circuit

### ISSUE THREAD

**Issue by convict999** [amadornes/SCM-Localization-Issues#186]
i forgot to deactivate timer before copying, circuit updating in hand, that cant help placing on a circuit either, rename as given? (does stop updating if inventory opened)

**Comment by amadornes** [comment]
I can't really reproduce it... :/

**Comment by GirafiStudios** [comment]
What version of SCM are you using @convict999 ? :)

**Comment by convict999** [comment]
it was 1.0.3 it seems fine now 1.0.4
