### ISSUE TITLE
Minecraft crash when clicking ender pulsar

### ISSUE THREAD

**Issue by FallenEagle1** [amadornes/SCM-Localization-Issues#188]
Pack: All the Mods v 1.42b
SCM version: 1.0.1
Log: http://pastebin.com/6ZL4vhia

![2016-11-10_16 40 53](https://cloud.githubusercontent.com/assets/22630113/20198916/a28e5ada-a764-11e6-8872-bad8203c613d.png)

Description: I had two circuits next to each other, as shown. When I right clicked the left ender pulsar with a screwdriver, minecraft completely crashed. I tried to replicate the issue by repeating all of my steps, but no luck so far.

**Comment by amadornes** [comment]
1.0.1 is a fairly buggy (and old-ish) version of SCM. Could you try the same setup using 1.0.2/1.03?

**Comment by FallenEagle1** [comment]
Yeah, I realize that it is two versions behind. I just know that you've worked hard to have just the circuit crash, and since I didn't see an issue that was similar to this, I thought I'd say something and try to track it down.

I'll get back with findings hopefully later today

**Comment by FallenEagle1** [comment]
Well, I can not recreate the bug in either 1.0.1 or in 1.0.3, so maybe this is just a one off, freak bug. For now I'll close this since I can't get it to show up again. Great job on the mod btw!

**Comment by amadornes** [comment]
Thanks :D
