### ISSUE TITLE
Crash: ProjectE + SCM blueprints

### ISSUE THREAD

**Issue by HellishINC** [amadornes/SCM-Localization-Issues#189]
Other players Log: http://paste.ee/p/41iUe
My log: https://gist.githubusercontent.com/HellishINC/b25726f9f7e26f49581598fb66c82e6e/raw/180f6376adb0f25d8c102044906d4203c2b534fb/crashlog (warning this thing is huge)

One of my players is having a reproducible crash. In order to do so, you must teach the ProjectE tablet one of the blueprint recipes. Once taught, hovering over it's icon results in a crash. We tried simply unlearning the blueprint but once it's learned hovering the item causes the game to crash.

**Comment by GirafiStudios** [comment]
That log does not contain the crash, so it is not really helpful. It sounds like this issue is on Project Es side though.

**Comment by HellishINC** [comment]
I updated with my log. Perhaps mine is helpful?

**Comment by amadornes** [comment]
Should be fixed in 1.0.4 :)

**Comment by amadornes** [comment]
Also, this is ProjectE's fault for trying to get the name of a stack with either a null or invalid NBT tag, though I've taken care of it in SCM directly.

**Comment by HellishINC** [comment]
I'll post a link to this issue on their issue tracker.

Cheers!
