### ISSUE TITLE
Divider/multiplier breaks after relog

### ISSUE THREAD

**Issue by wesserboy** [amadornes/SCM-Localization-Issues#191]
![schermafbeelding 2016-11-11 om 15 34 39](https://cloud.githubusercontent.com/assets/7784003/20218378/9e07a28a-a824-11e6-815a-d35b9c124dfa.png)

The following circuit divides the incoming signal by 2. This works fine. Then when i relog, it looks fine. When i turn the lever off, the output turns off, but when i turn the lever back on, the signal stays 0. 

Interestingly: changing the value of the constant, or disconnecting and reconnecting the wire coming from the constant seems to fix it. Changing the connection of the other wires doesn't help.

Exactly the same happens with the multiplier

EDIT: same thing happens when the circuit was placed using a blueprint or when the circuit is broken and placed down again.

Using SCM version 1.0.3

**Comment by amadornes** [comment]
Fixed!
