### ISSUE TITLE
Enhancement: Bundled support for analogue operators

### ISSUE THREAD

**Issue by wesserboy** [amadornes/SCM-Localization-Issues#192]
It would be cool if you could connect bundled wire to the operator components to do mass operations on every channel.

Example use cases:
- Set a constant value on every channel.
- Multiply every signal by 255 to amplify them.

**Comment by amadornes** [comment]
This is exactly why you have circuits in circuits, and why I haven't added any bundled-compatible components that alter the signal in any way ;)
