### ISSUE TITLE
Bundled cable input doesn't work with circuits on circuits

### ISSUE THREAD

**Issue by florianL21** [amadornes/SCM-Localization-Issues#194]
Output with bundled cables work, but the inputs don't.
Is it broken or is it just not implemented yet?
I'm on 1.04

**Comment by marcin212** [comment]
It doesn't work with bundled and normal redstone.
Tested on 1.0.4
Circuit: https://gist.github.com/34a4c56dcb6dfd469ea3261008567d6f
Vide: https://www.youtube.com/watch?v=H_q1009mGKE

**Comment by florianL21** [comment]
The in and output with normal redstone works for me, but the input with bundled doesn't work at all and the output with bundled cable sets the signals that comes out of the crircuits to the state that they would be in if nothing was connected at the input as soon as i place them on the circuit. Even if the input is a normal redstone and not a bundled one.

**Comment by reinder-s** [comment]
i have the same issue
![2016-11-12 8](https://cloud.githubusercontent.com/assets/11552821/20236110/fb410638-a8a8-11e6-88b4-34571530c365.png)
![2016-11-12 6](https://cloud.githubusercontent.com/assets/11552821/20236111/fb6eaf70-a8a8-11e6-8905-0c21dafd6a49.png)
![2016-11-12 7](https://cloud.githubusercontent.com/assets/11552821/20236112/fb6f3cf6-a8a8-11e6-8cc8-e66c17991b47.png)

**Comment by amadornes** [comment]
Already fixed :)
