### ISSUE TITLE
Lever activating itself causes BCOD.

### ISSUE THREAD

**Issue by jojotastic777** [amadornes/SCM-Localization-Issues#197]
When I connect a lever to itself on a circuit, the circuit crashes.

https://gist.github.com/anonymous/c08043c1d8cc706678aea6a0bd50cf2e

**Comment by SoftPoison** [comment]
Same happens with this circuit: https://gist.github.com/anonymous/4fd2937b7d91732e24b485c7920fd7f2

(Running version 1.0.4)

**Comment by amadornes** [comment]
@jojotastic777 Works fine for me in 1.0.4. Are you sure you're running the latest version?

@SoftPoison I don't see a lever there, so I'm not sure this is related in any way :/

**Comment by SoftPoison** [comment]
@amadornes I'm talking about using an external redstone source, such as a lever outside of the circuit. I'll update this comment with pics later

**Comment by jojotastic777** [comment]
Nope. Weird. Must have been a one-off, or the pack that I was using may have updated.
