### ISSUE TITLE
Wont Install

### ISSUE THREAD

**Issue by DeadWabbit** [amadornes/SCM-Localization-Issues#198]
Have curse client downloaded the file, moved to mods folder, went to curse installed.. shows on the install list.. start up direwolf 20 no mod active. Wont work.

**Comment by xavasxxv** [comment]
Which version of MC are you using? SCM is only for 1.10, unless you have a beta of Dire's 1.10 modpack, it won't work on 1.7.10...

**Comment by amadornes** [comment]
Sounds to me like you're trying to use the mod in 1.7.10 instead of 1.10.2, especially because the DW20 pack isn't out for 1.10 yet. Also, I'm not sure why else you'd have to download the mod using the Curse client and move it to the mods folder, since when you download it it's already in there.
