### ISSUE TITLE
Top of impregnated redstone stick always looks active

### ISSUE THREAD

**Issue by Inari-Whitebear** [amadornes/SCM-Localization-Issues#200]
So, just came across this :P Bit of a little thing but:
![](https://dl.dropboxusercontent.com/u/18783800/ShareX/2016/11/2016-11-12_12-23-52_3sImfM.png)

The top of these sticks always kinda looks like activated redstone, especially noticeable in the dark when a plate covers it, but no cable on top.

**Comment by amadornes** [comment]
That's because you're used to glowing wire and not regular "static" wire. Not a bug, they're not supposed to change :P

**Comment by Inari-Whitebear** [comment]
Non non, It should look off, but it looks on! I'm not saying it should change, just that it should have the default look of being off!

![](https://dl.dropboxusercontent.com/u/18783800/ShareX/2016/11/2016-11-13_15-25-24_8fUFam.png)

The colour of its top is that of activated redstone, but it should be that of deactivated
