### ISSUE TITLE
SCM's Timer is too expensive

### ISSUE THREAD

**Issue by Xiaminou** [amadornes/SCM-Localization-Issues#249]
From a few pieces of redstone and stone for a vanilla or RP2 or Project:Red timer to 3 ender pearls and a blaze rod for your first timer.
I tend to automate things as early as possible and some of those require a timer, now while there are other mods that provide timers that I could use I would rather use Super Circuit Maker's. However I find it way too expensive for early game. I got used to the cheap RP2 or more recently Project:Red recipes for a simple yet effective implementation of logic gates. With SCM operating on the same basis I don't understand why the timer would be so much more expensive than it's been in other mods.

anyway... TL;DR: Timer too expensive? yes/no?

**Comment by gDKdev** [comment]
I agree. There are block forms of every component coming and in comparison to other timers they are/would be very expensive. I would suggest to increase the cost of the circuit plate, because that is what makes the mod a bit overpowered, because with it you can compress a big circuit into a single block.
That would keep the balance

**Comment by MRebhan** [comment]
But you can make timers without the timer part, just a little bigger. When you have enough resources, you can compact it more

**Comment by jambonmcyeah** [comment]
just use crafttweaker to change the recipe

**Comment by Xiaminou** [comment]
I did, I just felt like it was an issue that needed to be addressed. But I seems like I'm the the only one to think that...

**Comment by dokranke** [comment]
I agreed, in comparison to other timers they are very expensive. But I think that the circuit plate is too cheap.

**Comment by Xiaminou** [comment]
Yeah, I think recipes overall could use some rebalancing.
