### ISSUE TITLE
Copying/breaking gates makes them unusable

### ISSUE THREAD

**Issue by PWN1109** [amadornes/SCM-Localization-Issues#26]
If you copy a gate with a middle click it makes it unresponsive to any signal updates

**Comment by amadornes** [comment]
Yes, they don't get invalidated. I'm already working on fixing it in the next version (I'm adding blueprints, so I've ran into this)

**Comment by amadornes** [comment]
Looking into it!

**Comment by amadornes** [comment]
I got this mostly fixed in RC3 and a full "fix" for it is coming in RC4. It's not 100% reliable, but it won't ever be. Just... don't break the circuit the same tick you pick it :P
