### ISSUE TITLE
Shift right click with screwdriver

### ISSUE THREAD

**Issue by duke17776** [amadornes/SCM-Localization-Issues#279]
Using direwolf20 pack on server. Shift right click initially worked but when i placed a ender pulsar I was no longer able to shift right-click on any circuit. persistent through server and client restarts, I am able to create single player circuit and it works as intended. Made both a new circuit board and a new screwdriver and the problem still persists.

**Comment by convict999** [comment]
with the exception of the palette you can't have items in offhand for shiftclicking with screwdriver to work

**Comment by duke17776** [comment]
Thank you so much, I took everything else off my char and dropped it in a chest other then that. any chance getting that added to the screwdriver tool tip, for idiots like me that wouldn't think of that?
