### ISSUE TITLE
lever update on world load

### ISSUE THREAD

**Issue by convict999** [amadornes/SCM-Localization-Issues#28]
A lever (on tiny circuit plate) that is still receiving power and has toggled its output state will self update and change its state on world load, where it does not update on base level as expected.
Repeatable

**Comment by amadornes** [comment]
I can't reproduce this anymore, so I imagine I've already fixed it?
If the bug persists after the next update, re-open the issue and tell me what exactly I need to do to reproduce it (or make a video) and I'll look into it :)
