### ISSUE TITLE
Cannot place Redstone Circuit under Farmland

### ISSUE THREAD

**Issue by Xiaminou** [amadornes/SCM-Localization-Issues#290]
so I wanted to do some redstone works on the ceiling of my farm's basement but I found out that you cannot place redstone circuits on the bottom of farmland.

![2016-12-16_16 04 15](https://cloud.githubusercontent.com/assets/8670392/21267190/9c2586d0-c3a9-11e6-9cc8-96632e75c93f.png)

Minecraft: 1.10.2
Forge: 2185
Mods: [list.txt](https://github.com/amadornes/SCM-Localization-Issues/files/657519/list.txt)

**Comment by brisingraerowing** [comment]
@Xiaminou 
Off topic, but what mod adds those caution tape like blocks (the yellow striped ones)? I like them.
Also, back on topic (kinda), this mod has a lot of bugs. It is rather early in development, though, so that's to be expected.

**Comment by Xiaminou** [comment]
It's Chisel, it adds a lot of very cool and easily accessible blocks, a must have for anyone who wants to decorate their base.

**Comment by brisingraerowing** [comment]
I'll have to look at it.

**Comment by simpson409** [comment]
farm land is not a full block, nor a micro block type. there are a lot more blocks like this.

**Comment by Xiaminou** [comment]
@simpson409 Except slabs and stuff like that works just fine, as far as I can tell farmland is the only one being weird.
