### ISSUE TITLE
Download SCM

### ISSUE THREAD

**Issue by Bottersnike** [amadornes/SCM-Localization-Issues#33]
Is there anywhere that SCM can be downloaded or is it still private?

Thanks,
Bottersnike

**Comment by amadornes** [comment]
It's still private. Currently only FCers and patrons have access to it, but it's really close to being released.

**Comment by majix560** [comment]
exactly how "_**close**_" is it?
It's been way too long since you said that for it to be true.

**Comment by amadornes** [comment]
Close... Enough...? :P
Soaryn is making me rewrite wires so they're more reliable. The whole point of making you wait is letting beta testers make sure it doesn't blow up as soon as you get it, and after all this time it's pretty much ready.

**Comment by 3TUSK** [comment]
> Soaryn

so xycraft is delayed again?
