### ISSUE TITLE
Visual Glitch with Circuit Board

### ISSUE THREAD

**Issue by OverloadedWolf** [amadornes/SCM-Localization-Issues#34]
Found this when messing around with it. If you look at the side of the multi-part, it has a ghosting effect.
![2016-10-24_05 14 54](https://cloud.githubusercontent.com/assets/7889127/19640613/89555fbc-99ab-11e6-9b3a-d5b906c792a0.png)

**Comment by marcin212** [comment]
I think it is caused by other mod. I have same problem with minecraft sign without SCM.

**Comment by OverloadedWolf** [comment]
Fair enough

**Comment by amadornes** [comment]
Yup, this is caused by another mod. There's not much I can do about it :/
