### ISSUE TITLE
unable to change redstone line to READ.

### ISSUE THREAD

**Issue by popps73x** [amadornes/SCM-Localization-Issues#352]
Currently playing Age of Engineering v1.0.2 with SCM 1.0.4 installed.

cannot change the redstone wire to read the signal from an Ender Pulsar or from a quartz resonator.  if i place a lever on the circuit it automatically gets the read signal shape on the wire. shift right clicking with the screwdriver does nothing.  looking at the keybindings i do not see anything that appears to be interfering.  (all default for the pack).

basic circuit is pulsar in the center with a line out in each direction.  Quartz resonator then more line to the edge of the plate.  went so far as to rewatch dires tutorial to see if i was doing it incorrectly.  

world is singleplayer.

**Comment by ouroborus** [comment]
Having something in your offhand will prevent that from working.

**Comment by Gaberboo** [comment]
Are you sure you shift-right-clicked, as opposed to right clicking?
