### ISSUE TITLE
Crash on Launch - Class Not Found Exception

### ISSUE THREAD

**Issue by Drullkus** [amadornes/SCM-Localization-Issues#41]
[Crashlog](https://paste.ee/p/qqc6w)

Attempted to launch with SCM 1.0.1 on Forge .2119 ("latest", as of yesterday). This crash occurs with and without other mods loaded. Looks like class 'mcmultipart.client.multipart.MultipartSpecialRenderer' is not found.

**Comment by GirafiStudios** [comment]
I'm pretty sure SCM requires MCMultipart, you only have RebornCore-Multipart

**Comment by Drullkus** [comment]
_Facedesk_
