### ISSUE TITLE
Left clicking on enlarged embeded circuits does not return circuit

### ISSUE THREAD

**Issue by tomatheb** [amadornes/SCM-Localization-Issues#42]
**Description**: Left clicking on an embedded circuit if you have enlarged it destroys it rather than returning the circuit. This happens both with and without the screwdriver in hand, and with and without palette and brush in the offhand.

**Steps to reproduce**: Create and break a circuit, place using scroll wheel to make larger (2x2 or 3x3), right click. Circuit is not returned.

**Version**: Beta 1.0.1 
**Pack**: FTB Presents HermitPack version 1.2.1 (with Mob Inhibitor Beta 1.2 and Super Circuit Maker added)

**Comment by amadornes** [comment]
Looking into it!

**Comment by amadornes** [comment]
Fixed! Will be in the next build :)
