### ISSUE TITLE
HttpComponents only client side

### ISSUE THREAD

**Issue by marcin212** [amadornes/SCM-Localization-Issues#44]
Sorry for that, but HttpComponents is only available on client side.
crash: http://hastebin.com/uzoroticer.md

**Comment by amadornes** [comment]
Oh... Welp... That's a pain... Any good alternatives? :/

**Comment by marcin212** [comment]
Do you want your own code or an external library, like Unirest(http://unirest.io/java.html)?

**Comment by amadornes** [comment]
If it's something I can ship myself, it'd be better than shading a lib, but I'll do it if it has to be done

**Comment by marcin212** [comment]
You can use my GistFactory: https://gist.github.com/marcin212/f7ebae2c375a493e81ea56b735a9acf2

**Comment by amadornes** [comment]
Fixed! :D
