### ISSUE TITLE
Circuits in Circuits Crash

### ISSUE THREAD

**Issue by maginator** [amadornes/SCM-Localization-Issues#46]
Hi, if i take a Redy Blueprint from the mod and would to add it in to a other circuit its crash.
and the its dosent Render. Tested with and Gate
Screenshot: http://imgur.com/a/JHt3l
Crash: http://pastebin.com/p86w4das
Magi

**Comment by amadornes** [comment]
Try updating Forge

**Comment by amadornes** [comment]
Yep. Confirmed to be caused by an old version of Forge!

**Comment by maginator** [comment]
Newest Forge 1.10.2 18.2.2122 and is dosent work

**Comment by maginator** [comment]
Oh forgott it im realy stiupid sry
