### ISSUE TITLE
Cable 'diode' keeping state

### ISSUE THREAD

**Issue by magik6k** [amadornes/SCM-Localization-Issues#48]
Reproduce: https://gfycat.com/SelfishUnripeArgentineruddyduck
Looking at this gif you can probably see what it's about. It also looks like it can be used as kind of (jk-?)flip-flop, right lever being set, left value.

**Comment by amadornes** [comment]
Odd... Will look into it. I've certainly noticed some oddities here and there with the new wire code, but I've never ran into this :/

**Comment by magik6k** [comment]
Been able to use it to create compact memory: https://gfycat.com/PlainInexperiencedCornsnake heh. 'It's not a bug it's a feature :p'

**Comment by amadornes** [comment]
Fixed! Will be in the next build :)
