### ISSUE TITLE
Exception while updating neighbours

### ISSUE THREAD

**Issue by Eroc33** [amadornes/SCM-Localization-Issues#49]
I placed an empty circuit plate among some others on a wall, but the plate didn't appear.
Then I broke the block the plate should have been placed on and triggered this crash.
[crash log](https://github.com/amadornes/SCM-Localization-Issues/files/572417/crash-2016-11-04_18.51.57-server.txt)

ETA:
When I reloaded the world the two circuits I placed the plate next to were sad, logs below:
https://gist.github.com/497f31161ff6ecc5e3d9afd112a5d91b
https://gist.github.com/b16869adaaf03ffeb70f72e0f0a0d635

**Comment by amadornes** [comment]
Fixed! :)
