### ISSUE TITLE
Some circuits error when placed after being copied with pick block.

### ISSUE THREAD

**Issue by Eroc33** [amadornes/SCM-Localization-Issues#51]
The following blueprint is a circuit that errors when selected and placed with pick block in creative mode, but only if the lever is powering the lamps when it is selected.

https://gist.github.com/anonymous/c5c46c218c5ab3f08517c956c12ef1c2

ETA:
If a blueprint is made when the lever is powered then that blueprint cannot be applied to a circuit.
Bad blueprint:
https://gist.github.com/37c5f6a03da034089cfe8bd19184ef6d

Edit 2:
If you create a circuit from the blueprint that can still be applied, then activate the lever that circuit also errors.
Circuit error log: https://gist.github.com/eb2ac7717e05618282dcd3ca9c14b93f

Edit 3:
Minimum erroring circuit: https://gist.github.com/f9afe6ceb59f45b3a7253b0d9fd5191d
![2016-11-04_19 45 58](https://cloud.githubusercontent.com/assets/599099/20020091/629e31b2-a2c7-11e6-8477-f41afb9916a0.png)

**Comment by marcin212** [comment]
I have the same problem. Error after placed : http://hastebin.com/uzimaxehok.rb

**Comment by amadornes** [comment]
Fixed! It was caused by the issues in vertical wire :)
