### ISSUE TITLE
Redstone impregnated sticks power transfer not working

### ISSUE THREAD

**Issue by jplee95** [amadornes/SCM-Localization-Issues#52]
The redstone impregnated sticks will not transfer the power when placed on non light gray wire going up. Upon starting with the light gray wire and changing the color after placing the redstone impregnated sticks up to the designated location, it will work.

Side note: Going down from colored wires works fine.

Second note: the redstone impregnated sticks are just broken. They seem to cause a major amount of my blue screened circuits.

**Comment by amadornes** [comment]
Yeah, can confirm they're quite derpy. Trying to figure out what's wrong with them atm.

**Comment by amadornes** [comment]
Fixed!
![ama-1478368228-1186](http://ss.amadornes.com/ama-1478368228-1186.png)
