### ISSUE TITLE
Analog components does not update itself on placement

### ISSUE THREAD

**Issue by Exidex** [amadornes/SCM-Localization-Issues#54]
If you have a circuit with an analog component on it, you remove and then place the component, the component itself will not update on placement.

**Comment by amadornes** [comment]
What do you mean it doesn't update? I'm trying to replicate it but I can't figure out what the problem is. Here's a video of me testing it: http://ss.amadornes.com/ama-1478297762-1177

**Comment by Exidex** [comment]
My fault, I was talking about output power level does not updating, you need to reconnect input to make it output proper value.

**Comment by amadornes** [comment]
Ah, yeah. There's no "set" output on the component, so it won't connect automatically like a lever would :)
