### ISSUE TITLE
NBT data exceding packet size limit

### ISSUE THREAD

**Issue by XFactHD** [amadornes/SCM-Localization-Issues#55]
When I place the circuit shown on the left (complexity: 1,464) into the circuit shown on the right (complexity: 1,9), the game hangs and the console shows an error about the packet being bigger than 32767 bytes. I know that this will always happen if the circuit has a complexity of almost 9 but because these simple circuits also excede the packet limit, I can only use stuff like AND gates in other circuits.
The setup:
![2016-11-04_21 19 47](https://cloud.githubusercontent.com/assets/11262040/20021242/4d0f4076-a2d5-11e6-9f02-0654b30936e0.png)
Circuits contained within the offending circuit:
![2016-11-04_21 30 06](https://cloud.githubusercontent.com/assets/11262040/20021419/f047ad28-a2d5-11e6-8871-6dfc45919a7b.png)

Forge: 1.10.2-12.18.2.2104
SCM: 1.0.1

**Comment by amadornes** [comment]
Already fixed in the next build :)

**Comment by XFactHD** [comment]
Ok, nice job!
