### ISSUE TITLE
Cables not changing

### ISSUE THREAD

**Issue by Raxxion** [amadornes/SCM-Localization-Issues#58]
If a color matches and you try to paint the cable it stays connected still instead of being a single cable like it should be.

**Comment by Exidex** [comment]
It is intended. Colored wires is not connecting to other colors only when you place wire. You can still connect two wires with different colors. This and bundled cables are only two features of colored wires.

**Comment by amadornes** [comment]
Exactly. The wires on a tile can connect to each other no matter what their color is.
