### ISSUE TITLE
Unable to break circuits that are not blank in creative mode

### ISSUE THREAD

**Issue by Heufneutje** [amadornes/SCM-Localization-Issues#60]
Found this while trying out SCM 1.0.1 in creative mode. This gif says it all:

![ezgif-2662085916](https://cloud.githubusercontent.com/assets/1357231/20025079/631f07f0-a2eb-11e6-9910-91ce1439fa16.gif)

It seems that as long as the circuit is blank, you can break it no problem, but as soon as it has data on it, either placed manually or from a red- or blueprint, you can't break it anymore in creative mode.

**Comment by Heufneutje** [comment]
Just to make sure that it wasn't one of the other mods I had installed I created a new instance with just SCM and the issue is there as well.

**Comment by Exidex** [comment]
It is intended to prevent to breaking circuits accidentally.

**Comment by gabor6505** [comment]
It works for me, did you try it with Shift + Left Click ?

**Comment by Heufneutje** [comment]
Ah, was just about to ask if there was a way around that. I did not realize you could shift click it, or that this was intended behavior. Thanks.

**Comment by amadornes** [comment]
Yep. It's there to prevent accidental breaking :)
