### ISSUE TITLE
Crash when Rotating Circuit

### ISSUE THREAD

**Issue by LiamJarvis** [amadornes/SCM-Localization-Issues#64]
http://pastebin.com/u4g3tFHP

Edit: Turned into pastebin (ama)

**Comment by amadornes** [comment]
Is there nothing else before that in the log? Because that isn't very helpful at all. It doesn't even say anything related to SCM in the stacktrace :/

**Comment by LiamJarvis** [comment]
Not from what I can tell I wasn't able to recreate it all I know is I rotated a circuit and then crash
