### ISSUE TITLE
Inventory Scanner dosent Update

### ISSUE THREAD

**Issue by maginator** [amadornes/SCM-Localization-Issues#65]
Hi, this Picture say all: http://imgur.com/a/MBJZ5

Magi

**Comment by amadornes** [comment]
Seems to work fine on my end. Try connecting it to just glowing wire, instead of attaching it to bundled and vertical wire (which seems to be a bit derpy in 1.0.1) and let me know if it still doesn't work.

**Comment by maginator** [comment]
Its dosent work
http://imgur.com/kAXZQh7

Magi

**Comment by convict999** [comment]
@maginator Its working, its an analouge output

**Comment by maginator** [comment]
@convict999 yes i now im to stiupid. after a little playing im check that its work

**Comment by amadornes** [comment]
I guess it can be closed now if it actually works :)
