### ISSUE TITLE
Sad Circuit Execption ideas

### ISSUE THREAD

**Issue by Joshwoo70** [amadornes/SCM-Localization-Issues#67]
some ideas : 
* when right clicked on a circuit with a sad exception.. post a gist github link. to the error.
* possible to add witty text? such as : "Abort, Retry, Fail?" , "have you tried turning it on and off again?"
PS : is it possible to add a wiki to github? i would like to know some functions.. subtractors,adders,multiplyers works...

**Comment by amadornes** [comment]
* Click on it with a multimeter. Been a thing since I added BCODs.
* Can do, but I don't see the need for it. I think the blue circuit with the sad face is probably enough :P
* Yep. I'll be working on a wiki as well as ingame documentation once things have settled down a bit :)
