### ISSUE TITLE
Sad blue circuit :(

### ISSUE THREAD

**Issue by Mr-Gelo** [amadornes/SCM-Localization-Issues#70]
Here is this circuit: https://gist.github.com/f2493f6891661be2b6d01f368ed1db04
I have made a lot of circuits in my world, but only the one with several vertical levels became broken :(
I used Forge ver. 12.18.2.2099 and SCM ver. 1.0.1.

I'm new to GitHub, so I apologize if I wrote this to the wrong place or missed something important.

**Comment by Mr-Gelo** [comment]
Found out simpler design. It seems, like wire on the second layer that interact with torch from the first layer is causing this problem.
![2016-11-05_23 51 39](https://cloud.githubusercontent.com/assets/23279054/20032429/2de4d5f2-a3bc-11e6-988d-1bab2e293d6d.png)

**Comment by amadornes** [comment]
Already fixed! This was caused by all the issues with vertical wire :)
