### ISSUE TITLE
wire keeps being powered even without signal when color is changed during power on

### ISSUE THREAD

**Issue by chrischtea** [amadornes/SCM-Localization-Issues#72]
setup:
switch outputs green redstone, which is connected to red redstone, which connects one greeen and one red redstone each via two bundled cable (A).
![2016-11-05_16 50 05](https://cloud.githubusercontent.com/assets/23280306/20031554/d0c20d32-a379-11e6-8d2a-8930c60d71c5.png)

problem:
when the switch is flipped, the green cable behind the bundled cable is lit, but not the red. (B) [see this [report](https://github.com/amadornes/SCM-Localization-Issues/issues/73) as well]
when changing the color of both red cables while the switch is on (first output, then inline) (C), the red output cable stays on even though the switch gets switched of (D)

**Comment by chrischtea** [comment]
installed mods:
chisels & bits 12.7
CC core 1.8+ 2.3.5.91
CC Lib 1.8+ 2.4.3.124
inventory tweaks 1.61-58
JEI 3.13.2.354
MCMultipart 1.3.0
NEI 1.8+ 2.1.2.163
SCM 1.0.1
Waila 1.7.0-B3_1.9.4

**Comment by amadornes** [comment]
Already fixed! :)
