### ISSUE TITLE
cable inputing into string of colored cable will be one transmitted trough bundled cable not last one

### ISSUE THREAD

**Issue by chrischtea** [amadornes/SCM-Localization-Issues#73]
setup:
![2016-11-05_17 02 21](https://cloud.githubusercontent.com/assets/23280306/20031615/9d92fe0c-a37a-11e6-937c-ec216b1446cc.png)
switch outputs to multiple connected, differently colored cables which ends in bundled cable (A)

problem:
only the color which gets the output of the witch is transmitted through the bundled cable (B, C)

**Comment by chrischtea** [comment]
installed mods:
chisels & bits 12.7
CC core 1.8+ 2.3.5.91
CC Lib 1.8+ 2.4.3.124
inventory tweaks 1.61-58
JEI 3.13.2.354
MCMultipart 1.3.0
NEI 1.8+ 2.1.2.163
SCM 1.0.1
Waila 1.7.0-B3_1.9.4

**Comment by amadornes** [comment]
Yep. Already fixed!
