### ISSUE TITLE
Crash when powering circuit in circuit and strange redstone behavior

### ISSUE THREAD

**Issue by Wieku** [amadornes/SCM-Localization-Issues#74]
Screenshot before recording: [click](https://img.wieku.me/2016-11-05+15:51:26.png)
1st video: [click](https://www.youtube.com/watch?v=E4wxp7VhNJA)
2nd video: [click](https://www.youtube.com/watch?v=AetVAIgbKic)
First circuit on 1st video started to crash after recording...
Version: Beta 1.0.1

**Comment by Wieku** [comment]
Circuit in Circuit bug #43

**Comment by Wieku** [comment]
#43

**Comment by amadornes** [comment]
I'm going to assume this is due to vertical wires being derpy. Should be fixed in the next build! :)
