### ISSUE TITLE
interface of ender pulsar opens on host, when guest right clicks ender pulsar

### ISSUE THREAD

**Issue by chrischtea** [amadornes/SCM-Localization-Issues#77]
in a singleplayer world, opened to LAN, when a player (not the host) opens the interface of the pulsar (or resonator) the interface is opened both for that player and the host. the interface is usable for the host and works cross dimensional (also in the nether)
installed mods:
chisels & bits 12.7
CC core 1.8+ 2.3.5.91
CC Lib 1.8+ 2.4.3.124
inventory tweaks 1.61-58
JEI 3.13.2.354
MCMultipart 1.3.0
NEI 1.8+ 2.1.2.163
SCM 1.0.1
Waila 1.7.0-B3_1.9.4

**Comment by amadornes** [comment]
Should be fixed now :)
