### ISSUE TITLE
Few issues with cables

### ISSUE THREAD

**Issue by dpeter99** [amadornes/SCM-Localization-Issues#82]
- [x] The corner is lit up:
![2016-11-05_18 30 13](https://cloud.githubusercontent.com/assets/7725817/20032231/0c1b20ba-a386-11e6-9e22-fe7b82299f50.png)
- [x] The wire reading incorrect color from bundled wire:
![2016-11-05_17 26 01](https://cloud.githubusercontent.com/assets/7725817/20032232/0c1d142e-a386-11e6-9442-d929751b8c00.png)
- [x] The redstone does not travel upwards:
![2016-11-05_17 53 50](https://cloud.githubusercontent.com/assets/7725817/20032233/0c20a94a-a386-11e6-8132-e2c9d6c251a2.png)

**Comment by amadornes** [comment]
All fixed! Will be in the next build :)
