### ISSUE TITLE
Segmented lamp texture

### ISSUE THREAD

**Issue by dpeter99** [amadornes/SCM-Localization-Issues#84]
Weird darker parts:
![2016-11-05_19 23 17](https://cloud.githubusercontent.com/assets/7725817/20032584/5e4927ea-a38d-11e6-84a3-374faedca67c.png)

**Comment by Mr-Gelo** [comment]
Did you colored them with palette? Looks like it.

**Comment by marcin212** [comment]
I think that, you colored it green(Look at palette)

**Comment by dpeter99** [comment]
They can be colored?

**Comment by dpeter99** [comment]
Wow OK closing. 
![2016-11-05_19 29 30](https://cloud.githubusercontent.com/assets/7725817/20032616/30034d4c-a38e-11e6-9e24-b5ca65cd499c.png)

**Comment by Mr-Gelo** [comment]
Yes!
