### ISSUE TITLE
Crash on opening component GUI with a Multimeter

### ISSUE THREAD

**Issue by Exidex** [amadornes/SCM-Localization-Issues#85]
Crash is a bit random. It happens sometimes when you open component GUI with a Multimeter.
To reproduce close and open GUI a lot of times.

![2016-11-05_19 18 43](https://cloud.githubusercontent.com/assets/16986685/20032603/e28c239a-a38d-11e6-8c3f-1570dd3df26f.png)

It also happens with 2 different crashlogs:
http://pastebin.com/nGuZhPWh
http://pastebin.com/jpvxyFa6

SCM export:
https://gist.github.com/anonymous/79616d7b22df3923bf4c579bfad88c47

**Comment by amadornes** [comment]
Fixed!
