### ISSUE TITLE
Bundled redstone keeps lit when inside of circuit on a circuit

### ISSUE THREAD

**Issue by UnRealDinnerbone** [amadornes/SCM-Localization-Issues#86]
The circuit on the left keeps the redstone lit the whole time (as seen on the right) http://ss.unrealdinnerbone.x10.bz/2016-11-05_13-51-24.png

Circuit on the left: https://gist.github.com/2859e223829d5b0e2eaac442c93e93a0

**Comment by amadornes** [comment]
This is intended as the wire on the inside is powering the one on the outside and vice versa. There will be a way to do one-way connections later on.

**Comment by Mr-Gelo** [comment]
I suggest that you don't delete the old two-ways type of connection when you implement the new system. The existence of two-ways connection is very useful for building compact circuits!

**Comment by amadornes** [comment]
Yes, but it's not very useful if the signal stays on forever (and the rest of the circuit I/O isn't bidirectional, so it makes no sense for bundled to be)
