### ISSUE TITLE
Multiplier does not update when an unpowered input is set to an output

### ISSUE THREAD

**Issue by JgamerXD** [amadornes/SCM-Localization-Issues#87]
Changing an unpowered connection to a multiplier from input to output does not update it, resulting in an output level of 0.
![2016-11-05_20 04 22](https://cloud.githubusercontent.com/assets/7403995/20032856/a064e122-a393-11e6-9c9d-3f7bd1278b97.png)

**Comment by amadornes** [comment]
Fixed! :D
