### ISSUE TITLE
After relog in world any wires between circuits aren't work

### ISSUE THREAD

**Issue by lllLeonid** [amadornes/SCM-Localization-Issues#91]
After relog in world any wires between circuits aren't work
![screenshot](https://cloud.githubusercontent.com/assets/10176655/20033408/673bc658-a3a8-11e6-9858-73aa8c4a5746.png)

**Comment by amadornes** [comment]
Can confirm! Looking into it :)

**Comment by amadornes** [comment]
That was surprisingly easy to fix. Done! :D
