### ISSUE TITLE
Wall mounted Circuits not working - different in all directions

### ISSUE THREAD

**Issue by DJKinggo13** [amadornes/SCM-Localization-Issues#92]
A simple example:
![screenshot_694](https://cloud.githubusercontent.com/assets/21091640/20033847/d59ce436-a3aa-11e6-9b99-92d940a0c233.png)
The expected outcome is the left lamp to be on because of the torch. 
Instead, none are on.
When I flip the lever:
![screenshot_695](https://cloud.githubusercontent.com/assets/21091640/20033851/f8c75022-a3aa-11e6-8048-d0ef6f754be2.png)
The expected outcome here is the top and right lamp to be on, and the left one to be off.
Instead, only the right one is on.

I am looking East in these pictures, here are the same 2 pictures looking in different directions:

West:
![screenshot_698](https://cloud.githubusercontent.com/assets/21091640/20033901/b88a8018-a3ac-11e6-92a3-475319efeca0.png)
![screenshot_699](https://cloud.githubusercontent.com/assets/21091640/20033902/bbf7c8dc-a3ac-11e6-9fe7-3b37cc8a40ad.png)

North & South (same results)
![screenshot_696](https://cloud.githubusercontent.com/assets/21091640/20033916/2ac279ba-a3ad-11e6-9524-5407e094aad4.png)
![screenshot_697](https://cloud.githubusercontent.com/assets/21091640/20033903/c8cf5d22-a3ac-11e6-84e0-68658f4dc0b4.png)

**Comment by amadornes** [comment]
That's odd... I fixed this a few weeks ago...

**Comment by amadornes** [comment]
Welp, that was a derp. I was converting the direction from cardinal (NSWE) to relative (FBLR) twice... Fixed!
