### ISSUE TITLE
Vertical circuits don't output

### ISSUE THREAD

**Issue by Jozufozu** [amadornes/SCM-Localization-Issues#93]
![See](https://cloud.githubusercontent.com/assets/21962423/20033850/d9713b9a-a367-11e6-947d-b8307a1bdff2.png)

**Comment by Jozufozu** [comment]
Duplicates #92

**Comment by lakksam** [comment]
This only seems to be a problem when it's rotated north-south. If you rotate the whole structure 90 degrees (so it's facing east-west) it works.
