### ISSUE TITLE
Bug: Minecraft crashes when placing one circuit into another one

### ISSUE THREAD

**Issue by gDKdev** [amadornes/SCM-Localization-Issues#95]
Minecraft crashes when i try to insert one of these circuits (https://gist.github.com/635fa1b4e8411125ab29c70ad5e11513 or https://gist.github.com/3f87a27f578c859ef8778d560705df35) into any circuit (an empty one or that one: https://gist.github.com/0a792ced20fedbe7a9b64c53f0b2de3a).

It has something to do with the networking...
Thanks for your help.

Attachments: Log & World Save
-----------------------------------
[fml-client-latest.log.txt](https://github.com/amadornes/SCM-Localization-Issues/files/573569/fml-client-latest.log.txt)
[SCM-Test.zip](https://github.com/amadornes/SCM-Localization-Issues/files/573570/SCM-Test.zip)

**Comment by amadornes** [comment]
Yep... Vanilla doesn't like long NBT tags... I'll keep you updated in #98
