### ISSUE TITLE
Directional, rotational and update weirdness.

### ISSUE THREAD

**Issue by Crazy-KSK** [amadornes/SCM-Localization-Issues#96]
1. [Link](http://i.imgur.com/l072yX8.jpg) No amount of trying to update the off corners seems to make the turn on, this happens regardless of orientation of the block-face the circuit is placed on i.e. walls.
I also had difficulty connecting the buggy corners to the outside with the screwdriver I had to rotate the circuit to do so.

2. [Here](http://i.imgur.com/hoFvFlh.png) the wire on the space between the block is buggy (the previous bug is also there), it only turns on if the wire is updated while redstone is on.
[Here](http://i.imgur.com/bhc1nC0.png) I broke the lamps on one side only. 
Now if the torches are broken the previously updated lamps stay on. [Link](http://i.imgur.com/bHsUmsr.png)
[Link](http://i.imgur.com/N5Fzqon.png) It updates correctly if the wire runs from the edge onto a board,  although only from left to right [Link](https://i.imgur.com/7H5QXWD.png). (I assume this is intended to work like this? would be more intuitive if the middle torch would connect to all 4 edges imho)
All of this also holds true if placed on a wall.

3. Copying the middle of [this](http://i.imgur.com/hQUCocA.png) part then pasting it and then rotating it results in the [edge](http://i.imgur.com/EZScJpU.png) being left behind.

**Comment by amadornes** [comment]
* #81 
* The seams between circuits shouldn't get any kind of world I/O. Will look into it :)
* Only the part inside the circuit's "bounds" gets rotated. Not really a bug, but I agree that we need a way of rotating bigger areas. (Already planned, will be added in the future)

**Comment by amadornes** [comment]
Fixed! :)
