### ISSUE TITLE
Circuit Crashes When I placed a simple circuit onto it.

### ISSUE THREAD

**Issue by rascalf78** [amadornes/SCM-Localization-Issues#99]
I made an OR gate but with an on off switch. It was a very simple circuit with a complexity of 0.442. When I picked it up and put it on a different circuit, it placed fine. But when I tried to power it, it crashed.

Here is the link to the crash log from the circuit.

[https://gist.github.com/anonymous/d98e4c2ed377d5f2c633d4d7b63e6f2e](https://gist.github.com/anonymous/d98e4c2ed377d5f2c633d4d7b63e6f2e)

**Comment by amadornes** [comment]
Yep, this is caused by a bug in posts that has already been fixed :)
